package py.com.fi.prototipo.exceptions;

/**
 * @author wtorales
 * @fecha 30/11/2021
 */
public enum ErrorCode {
    INTERNAL_ERROR,
    DATABASE_ERROR,
    ESTADO_INVALID_ERROR,
    CUSTOM_ERROR,
    NO_DATA_FOUND,
    UNAVAILABLE,
    UNAUTHORIZED,
    FORBIDDEN,
    BAD_REQUEST
}
